### ISSUE TITLE
Update GitHub action name

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/BranchValidator#9]
### **Description:**

Update the `action.yml`

Update the name of the GitHub action from **BranchValidator** to **Branch Validator**.  It simply needs a space between each word.

This can be done in the **action.yml** file.  Refer to example below.

```yml
name: 'BranchValidator' 👈🏼 Update this here
description: 'Checks if a GIT branch name is valid.'
author: 'Calvin Wilkinson (KinsonDigital)'
branding:
  icon: settings
  color: purple
```

![image](https://user-images.githubusercontent.com/85414302/179209814-ba9c621a-d336-4032-9bac-167666d0d86b.png)

### **Acceptance Criteria:**
- [x] Action name updated
